---
title: "Senegal-SST"
author: "DEP"
---

```{r}
library(earthdatalogin)
library(terra)
```

```{r}
earthdatalogin::edl_netrc(
  username = "dep22", # add your user name
  password = "s5cGJMApSNF" # add you password
)
```

```{r}
earthdatalogin:::edl_netrc_path()
```

```{r}
earthdatalogin::edl_netrc()
```

```{r}
short_name <- 'MUR-JPL-L4-GLOB-v4.1'
```

```{r}
#tbox <- c("2021-06-01", "2023-05-31")
tbox <- c("2021-06-01", "2021-06-02")
```

```{r}
results <- earthdatalogin::edl_search(
    short_name = short_name,
    version = "4.1",
    temporal = tbox
)
length(results) # how many links were returned
results[1:3] # let's see the first 3 of these links
```

```{r}
bbox <- c(xmin=17, ymin=14, xmax=18, ymax=15) 
bbox
```

```{r}
results <- earthdatalogin::edl_search(
    short_name = short_name,
    version = "4.1",
    temporal = tbox,
    bounding_box = paste(bbox,collapse=",")
)
length(results)
results[1:3]
```

```{r}
oi = results
```

```{r}
library(terra)
ras <- terra::rast(x = oi[1], vsi=TRUE)
plot(ras)
```

```{r}
short_name <- 'MUR-JPL-L4-GLOB-v4.1'
bbox <- c(xmin=17, ymin=14, xmax=18, ymax=15) 
tbox <- c("2021-06-01", "2021-06-02")

results <- earthdatalogin::edl_search(
  short_name = short_name,
  version = "4.1",
  temporal = tbox, 
  bounding_box = paste(bbox,collapse=",")
)
length(results)
results[1:3]
```

```{r}
ras <- terra::rast(results[1], vsi=TRUE)
```

```{r}
e <- terra::ext(c(xmin=17, xmax=18,  ymin=14, ymax=15 ))
rc <- terra::crop(ras, e)
rc
```

```{r}
plot(rc[[c(1, 2)]])
```

```{r}
ras_all <- terra::rast(results[c(1:2)], vsi = TRUE)
ras_all
```

```{r}
xmin = 17; ymin = 14; xmax = 18; ymax = 15;
```
